config/routes.rb
Rails.application.routes.draw do
    resources :posts do
    resources :comments, only: [:create, :destroy]
  end
    resources :bulletins do
    resources :posts
  end

  get 'review/write_review'
  get 'review/writing_review'
  get 'review/detail'
  get 'review/writing_reply'
  get 'review/index'

  get 'mypage/trace'
  get 'mypage/account'
  get 'mypage/codi_account'
  get 'mypage/save_box'
  get 'mypage/saving_box'
  get 'mypage/estimating_box'
  
  get 'mypage/estimating_box_detail/:id', to: 'mypage#estimating_box_detail'
  

  get 'hospital/index'
  get 'hospital/detail/:id', to: 'hospital#detail'
  post 'hospital/score_evaluate'

  get 'estimating/requesting'
  get 'estimating/requesting_content'
  post 'estimating/requesting_content'
  post 'estimating/requesting_complete'
  get 'estimating/requesting_complete'

  get 'estimating/codi_index'
  get 'estimating/manage'
  get 'estimating/manage_waiting'
  get 'estimating/manage_complete'
  get 'estimating/counsel/:id', to: 'estimating#counsel'
  get 'estimating/counsel_waiting'
  get 'estimating/counsel_complete'
  post 'estimating/counsel_content'
  get 'estimating/send_msg'
  

  devise_for :codis, controllers: {
        sessions: 'codis/sessions',
        registrations: 'codis/registrations',
        passwords: 'codis/passwords',
      }
  devise_for :users, controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations',
        passwords: 'users/passwords',
      }

  root 'home#index'
  get 'home/index'

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :bulletin
  has_many :comments, dependent: :destroy
  belongs_to :user
  mount_uploader :picture, PictureUploader
  acts_as_taggable

  def tag_list_fixed
    tag_list.to_s
  end

  def tag_list_fixed=(tag_list_string)
    self.tag_list = tag_list_string
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :set_bulletin
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [ :index, :show ]
  
  def index
    
    @tags = {
       'eye' => [ ['眼睛',"눈"], [['双眼皮',"쌍꺼풀"], ['眼形矫正术',"눈매교정"], ['开眼角',"트임"], ['眼睑下垂',"눈처짐"], ['眼袋 / 娇媚',"눈밑/애교"], [' 熊猫眼',"다크써클"], ['眼底脂肪',"눈밑 지"], ['再手术',"재수술"] ] ],
      'nose'=>[ ['鼻子',"코"], [ ['隆鼻术',"융비술"], ['歪鼻矫正术',"휜코 교정술 "], ['宽鼻矫正术',"축비술"], ['鹰钩鼻矫正术',"매부리코 교정술"], ['短鼻整形术',"짧은 코"], ['鼻头整形',"코 끝 성형"], ['鼻部玻尿酸',"코 필러"], ['再手术',"재수술"] ] ],
      'breast'=>[ ['乳房',"가슴"], [['隆胸术',"유방 확대술"], ['乳房下垂',"처진 가슴"], ['乳房缩小',"가슴 축소"], ['乳头整形',"유두 성형"], ['男士整形',"여성형 가슴"],['乳房重建术',"가슴 재건"],['再手术',"재수술"] ] ],
      'fat'=>[ ['吸脂',"지방"], [ ['手臂',"팔뚝"], ['腹部',"복부"], ['背',"등"],['大腿',"허벅지"],['小腿',"종아리"],['全身',"전신"], ['再手术',"재수술"]]],
      'skin'=>[ ['吸脂',"피부"], [ ['疤痕',"흉터"], ['青春痘',"여드름"], ['毛孔',"모공"], ['痣',"점"],['黑痣',"기미"], ['皱纹',"주름"]]],
      'petit'=>[ ['微创整形',"쁘띠"], [['肉毒杆菌',"보톡스"], ['方下巴',"사각 턱"], ['提升',"리프팅"], ['玻尿酸',"필러"],['Dermotoxin',"더마톡신"] ] ]
      }
    if params[:bulletin_id]
      @posts = @bulletin.posts.all
    else
      if params[:tag]
        @posts = Post.tagged_with(params[:tag])
      else
        @posts = Post.all
      end
      #최신글 부터 나열
      @posts = Post.order(created_at: :desc)
    end
  end

  def show
    @tags = {
       'eye' => [ ['眼睛',"눈"], [['双眼皮',"쌍꺼풀"], ['眼形矫正术',"눈매교정"], ['开眼角',"트임"], ['眼睑下垂',"눈처짐"], ['眼袋 / 娇媚',"눈밑/애교"], [' 熊猫眼',"다크써클"], ['眼底脂肪',"눈밑 지"], ['再手术',"재수술"] ] ],
      'nose'=>[ ['鼻子',"코"], [ ['隆鼻术',"융비술"], ['歪鼻矫正术',"휜코 교정술 "], ['宽鼻矫正术',"축비술"], ['鹰钩鼻矫正术',"매부리코 교정술"], ['短鼻整形术',"짧은 코"], ['鼻头整形',"코 끝 성형"], ['鼻部玻尿酸',"코 필러"], ['再手术',"재수술"] ] ],
      'breast'=>[ ['乳房',"가슴"], [['隆胸术',"유방 확대술"], ['乳房下垂',"처진 가슴"], ['乳房缩小',"가슴 축소"], ['乳头整形',"유두 성형"], ['男士整形',"여성형 가슴"],['乳房重建术',"가슴 재건"],['再手术',"재수술"] ] ],
      'fat'=>[ ['吸脂',"지방"], [ ['手臂',"팔뚝"], ['腹部',"복부"], ['背',"등"],['大腿',"허벅지"],['小腿',"종아리"],['全身',"전신"], ['再手术',"재수술"]]],
      'skin'=>[ ['吸脂',"피부"], [ ['疤痕',"흉터"], ['青春痘',"여드름"], ['毛孔',"모공"], ['痣',"점"],['黑痣',"기미"], ['皱纹',"주름"]]],
      'petit'=>[ ['微创整形',"쁘띠"], [['肉毒杆菌',"보톡스"], ['方下巴',"사각 턱"], ['提升',"리프팅"], ['玻尿酸',"필러"],['Dermotoxin',"더마톡신"] ] ]
      }
  end

  def new
    @post = @bulletin.posts.new
    @tags = {
       'eye' => [ ['眼睛',"눈"], [['双眼皮',"쌍꺼풀"], ['眼形矫正术',"눈매교정"], ['开眼角',"트임"], ['眼睑下垂',"눈처짐"], ['眼袋 / 娇媚',"눈밑/애교"], [' 熊猫眼',"다크써클"], ['眼底脂肪',"눈밑 지"], ['再手术',"재수술"] ] ],
      'nose'=>[ ['鼻子',"코"], [ ['隆鼻术',"융비술"], ['歪鼻矫正术',"휜코 교정술 "], ['宽鼻矫正术',"축비술"], ['鹰钩鼻矫正术',"매부리코 교정술"], ['短鼻整形术',"짧은 코"], ['鼻头整形',"코 끝 성형"], ['鼻部玻尿酸',"코 필러"], ['再手术',"재수술"] ] ],
      'breast'=>[ ['乳房',"가슴"], [['隆胸术',"유방 확대술"], ['乳房下垂',"처진 가슴"], ['乳房缩小',"가슴 축소"], ['乳头整形',"유두 성형"], ['男士整形',"여성형 가슴"],['乳房重建术',"가슴 재건"],['再手术',"재수술"] ] ],
      'fat'=>[ ['吸脂',"지방"], [ ['手臂',"팔뚝"], ['腹部',"복부"], ['背',"등"],['大腿',"허벅지"],['小腿',"종아리"],['全身',"전신"], ['再手术',"재수술"]]],
      'skin'=>[ ['吸脂',"피부"], [ ['疤痕',"흉터"], ['青春痘',"여드름"], ['毛孔',"모공"], ['痣',"점"],['黑痣',"기미"], ['皱纹',"주름"]]],
      'petit'=>[ ['微创整形',"쁘띠"], [['肉毒杆菌',"보톡스"], ['方下巴',"사각 턱"], ['提升',"리프팅"], ['玻尿酸',"필러"],['Dermotoxin',"더마톡신"] ] ]
      }
  end

  def edit
  end

  def create
    @post = @bulletin.posts.new(post_params)
    @post.user = current_user
    @post.save
    
    respond_to do |format|
      if @post.save
        format.html { redirect_to [@post.bulletin, @post], notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to [@post.bulletin, @post], notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to bulletin_posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_bulletin
      @bulletin = Bulletin.find(params[:bulletin_id]) if params[:bulletin_id]
    end

    def set_post
      if params[:bulletin_id]
        @post = @bulletin.posts.find(params[:id])
      else
        @post = Post.find(params[:id])
      end
    end

    def post_params
      params.require(:post).permit(:title, :content, :picture, :picture_cache, :tag_list_fixed)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
  def bulletin_name(bulletin_id)
    Bulletin.find(bulletin_id).title
  end
end

app/views/posts/post_types/_blog.html.erb
<!--게시판 옆에 설정 표시 -->
<h2><%= bulletin_name params[:bulletin_id] %> <small><%= link_to '설정', edit_bulletin_path(params[:bulletin_id])%></small></h2>

<% @posts.each do | post | %>
    <div class='post'>
      <td><%= post.title %> <small>( <%= post.comments.size %> )</small></td>
      <div class='content'><%= simple_format post.content %></div>
      <% if post.tag_list.size > 0 %>
        <div class='tag_list'><%= fa_icon('tags') + " " + tag_icons(post.tag_list) %></div>
      <% end %>
      <div>
          <%= link_to 'Show', [post.bulletin, post], class:'btn btn-default' %>
          <%= link_to 'Edit', edit_bulletin_post_path(post.bulletin, post), class:'btn btn-default' %>
          <%= link_to 'Destroy', [post.bulletin, post], method: :delete, data: { confirm: 'Are you sure?' }, class:'btn btn-default' %>
      </div>
    </div>
<% end %>

<% end %>
<br>

<%= link_to 'New Post', new_bulletin_post_path, class: 'btn btn-default' %>

app/views/posts/post_types/_bulletin.html.erb
<div class = "row">
  <div class="col s3">
       <!-- user info-->
          <div class="card-panel red lighten-2">
            <div class="caption center-align">
              <img src="<%current_user.profile_img%>" alt="" class="circle responsive-img" style = "height: 150px;
                      width: 150px;" > 
            </div>
            <span class="white-text"  style ="text-align: center">
              <h5><%=current_user.realname%></h5>
              <h6>年龄 : <%=current_user.age%> </h6>
              <h6>性別 : <%=current_user.sex%></h6>
            </span>
          </div>
            <!-- user info end-->
            <!-- user part test--보류>
            <!--<div class="card-panel white" style = "padding-top: 0px;    padding-right: 0px;    padding-bottom: 0px;    padding-left: 0px;">-->
            <!--    <div class = "row" style = "margin: 0.5rem 0 1rem 0;">-->
            <!--        <%# @tags.each do |key, value|%>-->
            <!--          <button name="<%#=key%>" class= "col s4 form-box" type="button" id= <%#=key%> style= "padding-right: 0px; padding-left: 0px;">-->
            <!--          <img src="/assets/part_picture/<%#= key %>.png" alt="" style = "height: 50px; width: 50px;" ></br>-->
            <!--          <%#= value[0][0] %>-->
            <!--          </button> -->
            <!--        <#% end %>-->
            <!--    </div>-->
            <!--</div>-->
            </div>
    <div class="col s9">
    <div class ="board">  
    <h2 class="header"><%= bulletin_name params[:bulletin_id] %></h2>
    <h2> <small><%= link_to '설정', edit_bulletin_path(params[:bulletin_id])%></small></h2>

  
    <table class="highlight">
   
    <thead>
    <tr>
      <th>Author</th>
      <th>Title</th>
      <th>Data actions</th>
      <th>Time</th>
    </tr>
    </thead>

    <tbody>
     
      <% @posts.each do |post| %>
        <tr>
         <td> <%= post.user.present? ? post.user.nickname : "n/a" %>  </td>
          <td><%= post.title %> <small>( <%= post.comments.size %> )</small></td>
          <td>
            <%= link_to 'Show', [post.bulletin, post], class:'btn btn-default' %>
            <%= link_to 'Edit', edit_bulletin_post_path(post.bulletin, post), class:'btn btn-default' %>
            <%= link_to 'Destroy', [post.bulletin, post], method: :delete, data: { confirm: 'Are you sure?' }, class:'btn btn-default' %>
          </td>
         <td><%= time_ago_in_words(post.created_at) %> ago</td>
        </tr>
        
      <% end %>
       
      
    </tbody>
    </table>


<%= link_to 'New Post', new_bulletin_post_path, class: 'btn btn-default' %>
</div></div></div>

app/views/posts/post_types/_gallery.html.erb
<div class = "row">
  <div class="col s3">
       <!-- user info-->
          <div class="card-panel red lighten-2">
            <div class="caption center-align">
              <img src="<%current_user.profile_img%>" alt="" class="circle responsive-img" style = "height: 150px;
                      width: 150px;" > 
            </div>
            <span class="white-text"  style ="text-align: center">
              <h5><%=current_user.realname%></h5>
              <h6>年龄 : <%=current_user.age%> </h6>
              <h6>性別 : <%=current_user.sex%></h6>
            </span>
          </div>
            <!-- user info end-->
            <!-- user part test보류-->
            <div class="card-panel white" style = "padding-top: 0px;    padding-right: 0px;    padding-bottom: 0px;    padding-left: 0px;">
                <div class = "row" style = "margin: 0.5rem 0 1rem 0;">
                    <% @tags.each do |key, value|%>
                      <button name="<%=key%>" class= "col s4 form-box" type="button" id= <%=key%> style= "padding-right: 0px; padding-left: 0px;">
                      <img src="/assets/part_picture/<%= key %>.png" alt="" style = "height: 50px; width: 50px;" ></br>
                      <%= value[0][0] %>
                      </button> 
                    <% end %>
                </div>
            </div>
            </div>


<div class="col s9">
  <div class ="board">  
    <h2 class="header">
      <%= bulletin_name params[:bulletin_id] %>
    </h2>
    <h2><small><%= link_to '설정', edit_bulletin_path(params[:bulletin_id])%></small></h2>


<div class='gallery'>
<div class='row'>
  <% @posts.each do | post | %>
      <div class='col l4 m4 s6  picture'>
        <div class='image'><%= link_to(image_tag(post.picture_url(:thumb)), [post.bulletin, post]) if post.picture? %></div>
        <div class='title'><%= post.title %></div>
        <div class='content'><%= post.content %></div>
        <% if post.tag_list.size > 0 %>
          <div class='tag_list'><%= fa_icon('tags') + " " + tag_icons(post.tag_list) %></div>
        <% end %>
        <div class='actions'>
            <%= link_to fa_icon('eye'), [post.bulletin, post] %>
            <%= link_to fa_icon('edit'), edit_bulletin_post_path(post.bulletin, post) %>
            <%= link_to fa_icon('trash'), [post.bulletin, post], method: :delete, data: { confirm: 'Are you sure?' } %>
        </div>
      </div>
  <% end %>
</div>
</div>
    

<br>

<%= link_to 'New Post', new_bulletin_post_path, class: 'btn btn-default' %>
</div></div></div>